### ISSUE TITLE
Building CRUD Functionality

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/code_institute_django_pp_4#6]
As a **User**, I can **perform CRUD action on database** so that **I can use and manipulate, including commenting, the data**

# **Acceptance Criteria:**

* Acceptance Criteria 1: the
* Acceptance Criteria 2: Transform design into Django app models
* Acceptance Criteria 3: Populate database using Superuser
* Acceptance Criteria 4: Test models and their functionality

# **Tasks:**

- [x]  Task 1: Build back-end driven design for models
- [x]  Task 2: update Readme.md file with the ERD 
- [x]  Task 3: Transform design into Django app models
- [x]  Task 4: Populate database using Superuser
- [ ] Task 5: build Templates
- [ ]  Task 5: Test models

**Comment by VladaAlek** [comment]
This user story can be closed, as the Templates will be made in the next iteration
