### ISSUE TITLE
Improving UI for DB/Models

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/code_institute_django_pp_4#7]
As a **user**, I can **view the book titles alphabetically** so that ** I can enhance the searchability of books**

# **Acceptance Criteria:**

* Acceptance Criteria 1: book titles are presented alphabetically

# **Tasks:**

- [ ]  Task 1: add method in Book Model in Apps Models.py
- [ ]  Task 2: migrate new model
- [ ]  Task 3: git push and deploy
