### ISSUE TITLE
Books title visibility in Reviews

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/code_institute_django_pp_4#8]
As a **user**, I can **see the book's title when review field is open** so that **I have visual confirmation that I have approached the expected book review**

# **Acceptance Criteria:**

* Acceptance Criteria 1: Appropriate text appears in the book review field
* Acceptance Criteria 2: Text contains the title of the book

# **Tasks:**

- [ ]  Task 1: refactor Review object in apps models.py
- [ ]  Task 2: test functionality
- [ ]  Task 3: git push and deploy
