### ISSUE TITLE
Landing Page Epics

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/code_institute_django_pp_4#9]
As a **user**, I am **introduces with the main page of the site** so that ** I get familiarized with the site's main concepts and navigate the site easily**

# **Acceptance Criteria:**

- [ ] Acceptance Criteria 1:  nav bar makes it possible to navigate between sites pages
- [ ] Acceptance Criteria 2: nav bar contains project's logo, clickable preferably 
- [ ] Acceptance Criteria 2: main section contains h1 and at least one <p/> section
- [ ] Acceptance Criteria 3: main section provides registration/log in section
- [ ] Acceptance Criteria 4:footer indicates the ownership 

# **Tasks:**

- [ ]  Task 1: create Django Base and Inheritance templates
- [ ]  Task 2: create HTML files
- [ ]  Task 3: create CSS files
- [ ]  Task 4: create and connect Django-Views and URLS for the landing page
- [ ] Task 5: test functionality
- [ ] Task 5: push and deploy
